## Coding Challenge

Welcome to our coding challenge! Your task is to develop a predictive model that estimates the amount of product (Titer) produced in the bioreactor for cell-culture experiments. This challenge simulates a real-world bioprocessing problem that we regularly encounter and is designed to evaluate your data analysis and modeling skills.

## Data Description

We provide time-dependent sequence data of a biological process, aggregated by experiment ID (column "Exp"), with varying durations. The objective is to predict the titer measured at the final time point.

### Variable Nomenclature:

- **X:{name}**: Represents measurements of process conditions, which are variables inherent to the process.
- **W:{name}**: Represents control conditions, which are measurements of the controlled parameters in the process.
- **Z:{name}**: Represents control setpoints, which are operator-defined control conditions that remain constant throughout the process.
- **Y:{name}**: Represents process attributes, which are measured at the end of the process.

## Objective

1. Perform any data analysis you consider relevant.
2. Build any data processing pipeline and model of your choice.
3. Evaluate the performance of your model.
4. Prepare your code so that it can generate predictions and results on a holdout test set (which we will provide before the interview).

The expected performance of your model may not be optimal. Don't worry about this and avoid spending excessive time improving the model itself. Your evaluation will focus on how you approach the problem, the clarity of your code, and your ability to justify your decisions.

Feel free to reach out with any questions you may have.

In [10]:
import pandas as pd
X = pd.read_csv(r"data\datahow_interview_train_data.csv")
X.head()

,RowID,Exp,Time[day],Z:FeedStart,Z:FeedEnd,Z:FeedRateGlc,Z:FeedRateGln,Z:phStart,Z:phEnd,Z:phShift,...,W:temp,W:pH,W:FeedGlc,W:FeedGln,X:VCD,X:Glc,X:Gln,X:Amm,X:Lac,X:Lysed
0,0,Exp 1,0,2.0,10.0,5.656566,6.818182,6.808081,6.479798,9.0,...,37.282828,6.808081,0.000000,0.000000,1.682644,2.853045,6.005418,0.100000,0.100000,0.000000
1,1,Exp 1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.282828,6.808081,0.000000,0.000000,3.617721,2.290199,3.598475,0.324724,1.348831,0.002831
2,2,Exp 1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.282828,6.808081,5.656566,6.818182,6.431879,0.752652,0.481756,0.687781,3.065268,0.000884
3,3,Exp 1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.282828,6.808081,5.656566,6.818182,10.279057,4.276583,2.516062,0.972871,4.196027,0.000000
4,4,Exp 1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.282828,6.808081,5.656566,6.818182,14.888965,7.350100,3.471558,1.322927,4.845310,0.000218

In [11]:
y = pd.read_csv(r"data\datahow_interview_train_targets.csv")
y.head()

   RowID    Exp  Time[day]      Y:Titer
0      0  Exp 1         10  2550.097032
1      1  Exp 2         10  1278.058508
2      2  Exp 3          9  1162.646534
3      3  Exp 4          9  1012.535606
4      4  Exp 5          8  1132.710237